services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: iris-db
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d iris-db"]
      interval: 5s
      timeout: 5s
      retries: 30 # high value for VM compatibility
    restart: on-failure
